"""Add notification preferences table

Revision ID: 12b1ea7bc342
Revises: b49bb9f3e68c
Create Date: 2025-12-05 15:52:57.376280

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12b1ea7bc342"
down_revision: Union[str, Sequence[str], None] = "b49bb9f3e68c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=True),
        sa.Column("email_enabled", sa.Boolean(), nullable=True),
        sa.Column("task_shared_with_me", sa.Boolean(), nullable=True),
        sa.Column("task_completed", sa.Boolean(), nullable=True),
        sa.Column("comment_on_my_task", sa.Boolean(), nullable=True),
        sa.Column("task_due_soon", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
