"""Add updated_at field

Revision ID: 2a7dd1d128a5
Revises: 6cd49ec8be57
Create Date: 2025-12-03 13:42:26.994093

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a7dd1d128a5"
down_revision: Union[str, Sequence[str], None] = "6cd49ec8be57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_comments", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_comments", "updated_at")
    # ### end Alembic commands ###
