"""add_user_profile_fields

Revision ID: 6598de72eb49
Revises: 03d3672a4d05
Create Date: 2025-12-18 13:56:25.543008

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6598de72eb49"
down_revision: Union[str, Sequence[str], None] = "03d3672a4d05"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("users", sa.Column("email_verified", sa.Boolean(), nullable=True))
    op.add_column("users", sa.Column("verification_code", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("verification_expires", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "verification_expires")
    op.drop_column("users", "verification_code")
    op.drop_column("users", "email_verified")
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
