"""Add password reset columns to users

Revision ID: a144594cccf5
Revises: 72bcc27d54a7
Create Date: 2025-12-20 16:03:59.530312

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a144594cccf5"
down_revision: Union[str, Sequence[str], None] = "72bcc27d54a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_reset_token", sa.String(), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "password_reset_token_expires", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_token_expires")
    op.drop_column("users", "password_reset_token")
    # ### end Alembic commands ###
