"""Add task_shares_table

Revision ID: b49bb9f3e68c
Revises: 0bff0849beb8
Create Date: 2025-12-03 21:14:22.360634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b49bb9f3e68c'
down_revision: Union[str, Sequence[str], None] = '0bff0849beb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('shared_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('shared_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'shared_with_user_id', name='unique_task_share')
    )
    op.create_index(op.f('ix_task_shares_id'), 'task_shares', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_shares_id'), table_name='task_shares')
    op.drop_table('task_shares')
    # ### end Alembic commands ###
